import type { Metadata } from 'next';
import { Ubuntu as Font } from 'next/font/google';

import { GlobalProvider } from '@/context/GlobalContext';

import '../global.css';

const inter = Font({ subsets: ['latin'], weight: ['400', '500', '700'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <head>
        <meta charSet='UTF-8' />
        <meta
          name='viewport'
          content='width=device-width, initial-scale=1.0'
        />
        <title>Multi Steps Form by Devtor14oo</title>
      </head>
      <body className={`${inter.className} grid place-items-center w-screen min-h-screen  bg-Magnolia`}>
        <GlobalProvider>{children}</GlobalProvider>
      </body>
    </html>
  );
}
