import '../global.css';
import type { Metadata } from 'next';
import { Ubuntu as Font } from 'next/font/google';

const inter = Font({ subsets: ['latin'], weight: ['400', '500', '700'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={`${inter.className} flex w-full h-screen justify-center items-center bg-Magnolia`}>{children}</body>
    </html>
  );
}
